server:
  port: 8400
spring:
  profiles:
    active: dev
zuul:
  routes:
    kyj-cloud-consumer: /consumer2/**
    kyj-cloud-provider: /provider2/**
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 80000
